# Generated by Django 2.2.2 on 2019-07-05 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190705_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', separatedvaluesfield.models.SeparatedValuesField(max_length=20)),
                ('y', separatedvaluesfield.models.SeparatedValuesField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 0, 24, 106283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 0, 24, 105286, tzinfo=utc)),
        ),
    ]
