# Generated by Django 2.2.2 on 2019-07-05 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190705_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 22, 56, 406525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 22, 56, 406525, tzinfo=utc)),
        ),
    ]
