# Generated by Django 2.2.2 on 2019-07-08 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190705_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='style',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 5, 29, 2, 572156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 5, 29, 2, 572156, tzinfo=utc)),
        ),
    ]
